#!/usr/bin/env python3
"""Build script - writes the complete fdv_chart.py"""

TARGET = r'd:\FDV\git\fdv_dashboard\dev\aitools\fdv_chart\fdv_chart.py'

LINES = [
    '#!/usr/bin/env python3',
    '"""',
    'FDV Chart Parser  -  web UI for filtering and plotting FDV log files',
    'Port: 5058   URL: http://localhost:5058',
    '"""',
    'import os, re, csv, json, uuid, io, sys, tempfile',
    'from pathlib import Path',
    'from http.server import HTTPServer, BaseHTTPRequestHandler',
    'from urllib.parse import urlparse, parse_qs',
    '',
    'parsed_cache = {}   # csv_id -> {headers, rows}',
    '',
    '# ---------------------------------------------------------------------------',
    '# FDV OUTPUT line parser  (based on guide_to_fdvlog.txt)',
    '# ---------------------------------------------------------------------------',
    'HEADERS = [',
    "    'Line#','DUT','Result','tname','testname',",
    "    'BLK','PAGE','PAGETYPE','PAGEMAP','WL','SB','BL',",
    "    'STEP','DECK','VCC','VCCQ','TEMP','TAC','TM',",
    "    'nBytes','nFailBytes','BYBER','nFailBits','RBER','RBER_Limit',",
    "    'FDV_File','FailData'",
    ']',
    '',
    'def _tok(tname, pat, default=""):',
    '    m = re.search(pat, tname, re.I)',
    '    return m.group(1) if m else default',
    '',
    'def parse_fdv_output_line(line):',
    '    """Parse one FDV OUTPUT line into a list of values matching HEADERS."""',
    "    m = re.match(r'FDV OUTPUT \\[([^\\]]+)\\]:\\s*(.+)', line.strip(), re.I)",
    '    if not m:',
    '        return None',
    '    bracket, rest = m.group(1), m.group(2)',
    '',
    '    fdv_path_tname, _, conds_str = bracket.partition("::")',
    "    fdv_file = os.path.basename(fdv_path_tname.replace('\\\\', '/').replace('\\\\\\\\', '/'))",
    '',
    '    tname_and_conds = conds_str',
    "    tname = tname_and_conds.split(',')[0].strip() if tname_and_conds else ''",
    "    conds_raw = ','.join(tname_and_conds.split(',')[1:]) if ',' in tname_and_conds else ''",
    '',
    '    conds = {}',
    "    for tok in conds_raw.split(','):",
    "        if '=' in tok:",
    "            k, _, v = tok.partition('=')",
    '            conds[k.strip().upper()] = v.strip()',
    '',
    "    testname = re.sub(r'\\.FDV$', '', fdv_file, flags=re.I)",
    '',
    "    blk    = _tok(tname, r'BLK[_:](\\d+(?:[_:]\\d+)*)')",
    "    page   = _tok(tname, r'P(?:AGE|G)[_:](\\d+)')",
    "    pgtype = _tok(tname, r'PGTYPE[_:]([A-Za-z]+)')",
    "    pm_src = tname + ' ' + testname",
    "    pgmap  = ''",
    "    for tag in ('QLC','TLC','MLC','SLC','SSLC','DSLC'):",
    '        if tag.lower() in pm_src.lower():',
    '            pgmap = tag; break',
    "    wl     = _tok(tname, r'WL[_:](\\d+)')",
    "    sb     = _tok(tname, r'SB[_:](\\d+)')",
    "    bl     = _tok(tname, r'BL[_:](\\d+)')",
    "    step   = _tok(tname, r'STEP[_:](\\d+)')",
    "    deck   = _tok(tname, r'(UD|LD|MD)', '').upper()",
    '',
    "    vcc  = conds.get('VCC','')",
    "    vccq = conds.get('VCCQ','')",
    "    temp = conds.get('TEMP', conds.get('DUTTEMP',''))",
    "    tac  = conds.get('TAC','')",
    "    tm   = conds.get('TM','')",
    '',
    "    parts = [p.strip() for p in rest.split(',')]",
    "    dut        = parts[0] if len(parts) > 0 else ''",
    "    result     = parts[1] if len(parts) > 1 else ''",
    "    nbytes     = parts[2] if len(parts) > 2 else ''",
    "    nfailbytes = parts[3] if len(parts) > 3 else ''",
    "    byber      = parts[4] if len(parts) > 4 else ''",
    "    nfailbits  = parts[5] if len(parts) > 5 else ''",
    "    rber       = parts[6] if len(parts) > 6 else ''",
    "    rber_lim   = parts[7] if len(parts) > 7 else ''",
    "    faildata   = ','.join(parts[8:]) if len(parts) > 8 else ''",
    '',
    '    return [',
    "        '',  # Line# filled by caller",
    '        dut, result, tname, testname,',
    '        blk, page, pgtype, pgmap,',
    '        wl, sb, bl,',
    '        step, deck,',
    '        vcc, vccq, temp, tac, tm,',
    '        nbytes, nfailbytes, byber,',
    '        nfailbits, rber, rber_lim,',
    '        fdv_file, faildata',
    '    ]',
    '',
    '',
    'def parse_log_file(file_path, regex_pattern=None, include_mode=True):',
    '    """Parse log file. Returns (headers, rows)."""',
    '    compiled = None',
    '    if regex_pattern:',
    '        try:',
    '            compiled = re.compile(regex_pattern)',
    '        except re.error as e:',
    "            raise ValueError('Invalid regex: ' + str(e))",
    '',
    '    rows = []',
    '    lnum = 0',
    "    with open(file_path, 'r', encoding='utf-8', errors='ignore') as fh:",
    '        for raw in fh:',
    '            lnum += 1',
    '            line = raw.strip()',
    '            if not line:',
    '                continue',
    '            if compiled:',
    '                hit = compiled.search(line)',
    '                if include_mode and not hit:',
    '                    continue',
    '                if not include_mode and hit:',
    '                    continue',
    '            parsed = parse_fdv_output_line(line)',
    '            if parsed is None:',
    "                parsed = [''] * len(HEADERS)",
    '                parsed[3] = line',
    "            parsed[0] = str(lnum)",
    '            rows.append(parsed)',
    '',
    '    return HEADERS, rows',
    '',
    '',
    '# ---------------------------------------------------------------------------',
    '# numeric extractor for plot',
    '# ---------------------------------------------------------------------------',
    'def extract_numeric(val, rx=None):',
    '    """Extract a float from val, optionally via a regex group."""',
    '    if rx:',
    '        m = re.search(rx, str(val))',
    '        if not m:',
    '            return None',
    '        val = m.group(1) if m.lastindex else m.group(0)',
    '    try:',
    '        return float(str(val).strip())',
    '    except Exception:',
    '        return None',
    '',
    '',
    '# ---------------------------------------------------------------------------',
    '# HTML / JS',
    '# ---------------------------------------------------------------------------',
    'def get_html():',
]

# Build the HTML string using join to avoid any escaping issues
HTML_LINES = [
    "    return '''<!DOCTYPE html>",
    '<html lang="en">',
    '<head>',
    '<meta charset="utf-8">',
    '<title>FDV Chart Parser</title>',
    '<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.3/dist/chart.umd.min.js"></script>',
    '<style>',
    '*{box-sizing:border-box}',
    'body{font-family:Arial,sans-serif;margin:0;padding:8px 14px;background:#f5f5f5}',
    'h1{margin:6px 0 2px;font-size:1.3em;color:#333}',
    '.top-form{background:#fff;border:1px solid #ccc;border-radius:6px;padding:10px 14px;margin-bottom:8px}',
    '.top-form label{font-size:.85em;font-weight:bold;color:#555}',
    '.row{display:flex;gap:10px;flex-wrap:wrap;align-items:flex-start;margin-top:4px}',
    '.row textarea,.row input[type=text]{flex:1;min-width:180px;font-family:monospace;font-size:.82em;padding:5px;border:1px solid #ccc;border-radius:4px}',
    '.row textarea{height:34px;resize:none}',
    '.btn{padding:7px 16px;background:#0066cc;color:#fff;border:none;border-radius:4px;cursor:pointer;font-size:.88em}',
    '.btn:hover{background:#0052a3}',
    '.btn.sec{background:#5a6268}.btn.sec:hover{background:#434a50}',
    '#msg{padding:7px 12px;border-radius:4px;display:none;font-size:.85em;margin:4px 0}',
    '#msg.ok{background:#d4edda;color:#155724;border:1px solid #c3e6cb}',
    '#msg.err{background:#f8d7da;color:#721c24;border:1px solid #f5c6cb}',
    '#msg.inf{background:#d1ecf1;color:#0c5460;border:1px solid #bee5eb}',
    '#info-bar{font-size:.82em;color:#555;margin:2px 0;display:none}',
    '/* PLOT PANEL */',
    '#plot-section{display:none;background:#fff;border:1px solid #ccc;border-radius:6px;padding:10px 14px;margin-bottom:8px}',
    '#plot-section h3{margin:0 0 6px;font-size:1em;color:#444}',
    '.plot-row{display:flex;gap:8px;flex-wrap:wrap;align-items:flex-end;margin-bottom:6px}',
    '.plot-row label{font-size:.8em;color:#555;display:flex;flex-direction:column;gap:2px}',
    '.plot-row select,.plot-row input{padding:4px 6px;border:1px solid #ccc;border-radius:3px;font-size:.82em}',
    '.plot-row input[type=text]{width:160px}',
    '#chart-wrap{position:relative;height:320px;background:#fafafa;border:1px solid #eee;border-radius:4px}',
    '/* TABLE */',
    '#dl-row{margin:4px 0;display:none}',
    '#table-container{overflow:auto;max-height:calc(100vh - 40px);border:1px solid #ddd;border-radius:4px;display:none;margin:6px 0}',
    'table{width:100%;border-collapse:collapse;font-size:.78em}',
    'th,td{padding:4px 8px;text-align:left;border-bottom:1px solid #eee;white-space:nowrap}',
    'th{background:#f0f0f0;font-weight:bold;position:sticky;top:0;z-index:1}',
    'tr:hover{background:#f5f5f5}',
    '</style>',
    '</head>',
    '<body>',
    '<h1>FDV Chart Parser</h1>',
    '',
    '<!-- CONTROL FORM -->',
    '<div class="top-form">',
    '  <div class="row">',
    '    <div style="flex:0 0 auto">',
    '      <label>Log File</label><br>',
    '      <input type="file" id="file-input" accept=".txt,.log,.csv" style="margin-top:4px">',
    '    </div>',
    '    <div style="flex:1;min-width:220px">',
    '      <label>Regex Filter</label>',
    '      <textarea id="regex-input" placeholder="^FDV OUT.*WL.*SB.*BL"></textarea>',
    '    </div>',
    '    <div style="flex:0 0 auto">',
    '      <label>Mode</label><br>',
    '      <label style="font-weight:normal"><input type="radio" name="fmode" value="include" checked> Include</label>&nbsp;',
    '      <label style="font-weight:normal"><input type="radio" name="fmode" value="exclude"> Exclude</label>',
    '    </div>',
    '    <div style="flex:0 0 auto;align-self:flex-end">',
    '      <button class="btn" onclick="parseFile()">&#9654; Parse</button>&nbsp;',
    '      <button class="btn sec" onclick="resetAll()">&#10005; Clear</button>',
    '    </div>',
    '  </div>',
    '</div>',
    '',
    '<div id="msg"></div>',
    '<div id="info-bar"></div>',
    '',
    '<!-- PLOT SECTION (above table) -->',
    '<div id="plot-section">',
    '  <h3>XY Plot</h3>',
    '  <div class="plot-row">',
    '    <label>X Column<select id="x-col"></select></label>',
    '    <label>X Regex (group 1)<input type="text" id="x-rx" placeholder="optional"></label>',
    '    <label>Y Column<select id="y-col"></select></label>',
    '    <label>Y Regex (group 1)<input type="text" id="y-rx" placeholder="optional"></label>',
    '    <label>Color By<select id="c-col"><option value="">-- none --</option></select></label>',
    '    <label>Type<select id="chart-type"><option value="scatter">Scatter</option><option value="line">Line</option></select></label>',
    '    <label>Max Pts<input type="text" id="max-pts" value="5000" style="width:70px"></label>',
    '    <button class="btn" onclick="drawPlot()" style="align-self:flex-end">&#9654; Plot</button>',
    '  </div>',
    '  <div id="chart-wrap"><canvas id="myChart"></canvas></div>',
    '  <div id="plot-info" style="font-size:.78em;color:#666;margin-top:3px"></div>',
    '</div>',
    '',
    '<!-- DOWNLOAD + TABLE -->',
    '<div id="dl-row">',
    '  <button class="btn sec" onclick="downloadCSV()">&#8595; Download CSV</button>',
    '</div>',
    '<div id="table-container">',
    '  <table id="result-table"></table>',
    '</div>',
    '',
    '<script>',
    'let currentData=null, currentCsvId=null, chartInst=null;',
    '',
    "function showMsg(txt,cls){const e=document.getElementById('msg');e.textContent=txt;e.className=cls;e.style.display='block'}",
    "function showInfo(html){const e=document.getElementById('info-bar');e.innerHTML=html;e.style.display='block'}",
    '',
    '// Parse',
    'async function parseFile(){',
    "  const file=document.getElementById('file-input').files[0];",
    "  if(!file){showMsg('Select a file first','err');return}",
    "  showMsg('Parsing '+file.name+'...','inf');",
    '  const form=new FormData();',
    "  form.append('file',file);",
    "  form.append('regex',document.getElementById('regex-input').value.trim());",
    "  form.append('mode',document.querySelector('input[name=\"fmode\"]:checked').value);",
    '  try{',
    "    const resp=await fetch('/parse',{method:'POST',body:form});",
    '    const r=await resp.json();',
    "    if(!r.success){showMsg('Error: '+r.error,'err');return}",
    '    currentData=r; currentCsvId=r.csv_id;',
    '    const tot=r.total_rows, shown=r.rows.length;',
    "    showMsg('Parsed '+tot.toLocaleString()+' rows (showing '+shown.toLocaleString()+' in table)','ok');",
    "    showInfo('<b>Total:</b> '+tot.toLocaleString()+' rows &nbsp;|&nbsp; <b>Columns:</b> '+r.headers.length+",
    "             (tot>shown ? ' &nbsp;|&nbsp; <b style=\"color:#c00\">Displaying first '+shown.toLocaleString()+'</b>':''));",
    '    renderTable(r.headers,r.rows);',
    "    document.getElementById('dl-row').style.display='block';",
    "    document.getElementById('table-container').style.display='block';",
    '    populatePlotSelectors(r.headers);',
    "    document.getElementById('plot-section').style.display='block';",
    '    setTimeout(drawPlot,250);',
    "  }catch(e){showMsg('Network error: '+e,'err')}",
    '}',
    '',
    '// Table',
    'function renderTable(headers,rows){',
    "  const t=document.getElementById('result-table');",
    "  let h='<thead><tr>'+headers.map(x=>'<th>'+x+'</th>').join('')+'</tr></thead><tbody>';",
    "  rows.forEach(r=>{h+='<tr>'+r.map(c=>'<td>'+(c||'')+'</td>').join('')+'</tr>'});",
    "  t.innerHTML=h+'</tbody>';",
    '}',
    '',
    'function downloadCSV(){',
    "  if(!currentCsvId){showMsg('No data','err');return}",
    "  window.location.href='/download/'+currentCsvId;",
    '}',
    '',
    'function resetAll(){',
    "  document.getElementById('file-input').value='';",
    "  document.getElementById('regex-input').value='';",
    "  ['msg','info-bar','dl-row','table-container','plot-section'].forEach(id=>{",
    "    document.getElementById(id).style.display='none';",
    '  });',
    '  if(chartInst){chartInst.destroy();chartInst=null}',
    '  currentData=null; currentCsvId=null;',
    '}',
    '',
    '// Plot',
    "const COLORS=['#0066cc','#cc3300','#009933','#cc6600','#6600cc','#007777','#cc0066'];",
    '',
    'function populatePlotSelectors(headers){',
    "  ['x-col','y-col','c-col'].forEach(id=>{",
    '    const sel=document.getElementById(id);',
    '    const oldVal=sel.value;',
    "    sel.innerHTML=(id==='c-col'?'<option value=\"\">-- none --</option>':'');",
    "    headers.forEach(h=>{const o=document.createElement('option');o.value=h;o.textContent=h;sel.appendChild(o)});",
    "    sel.value=oldVal||'';",
    '  });',
    '  function trySet(id,candidates){',
    '    const sel=document.getElementById(id);',
    '    for(const c of candidates){',
    '      for(const opt of sel.options){if(opt.value===c){sel.value=c;return}}}}',
    "  trySet('x-col',['WL','wl','Wl']);",
    "  trySet('y-col',['RBER','rber','Rber']);",
    "  trySet('c-col',['DUT','dut','Result','result']);",
    '}',
    '',
    'async function drawPlot(){',
    "  const xcol=document.getElementById('x-col').value;",
    "  const ycol=document.getElementById('y-col').value;",
    '  if(!xcol||!ycol||!currentCsvId){return}',
    "  const xrx=document.getElementById('x-rx').value.trim();",
    "  const yrx=document.getElementById('y-rx').value.trim();",
    "  const ccol=document.getElementById('c-col').value;",
    "  const ctype=document.getElementById('chart-type').value;",
    "  const maxp=parseInt(document.getElementById('max-pts').value)||5000;",
    '  const params=new URLSearchParams({csv_id:currentCsvId,x_col:xcol,y_col:ycol,',
    '    chart_type:ctype,max_points:maxp});',
    "  if(xrx)params.set('x_regex',xrx);",
    "  if(yrx)params.set('y_regex',yrx);",
    "  if(ccol)params.set('color_col',ccol);",
    "  const resp=await fetch('/plot_data?'+params.toString());",
    '  const r=await resp.json();',
    "  if(!r.success){document.getElementById('plot-info').textContent='Plot error: '+r.error;return}",
    '  const groupMap={};',
    "  r.points.forEach(p=>{const g=p.g||'data';if(!groupMap[g])groupMap[g]=[];groupMap[g].push({x:p.x,y:p.y})});",
    '  let ci=0;',
    '  const datasets=Object.entries(groupMap).map(([label,pts])=>{',
    '    const col=COLORS[ci++%COLORS.length];',
    "    return{label,data:pts,backgroundColor:col+'aa',borderColor:col,",
    '           pointRadius:3,pointHoverRadius:5,',
    "           showLine:(ctype==='line'),tension:0.1,fill:false};",
    '  });',
    '  if(chartInst)chartInst.destroy();',
    "  const ctx=document.getElementById('myChart').getContext('2d');",
    '  chartInst=new Chart(ctx,{',
    "    type:'scatter',",
    '    data:{datasets},',
    '    options:{',
    '      responsive:true,maintainAspectRatio:false,',
    '      plugins:{legend:{display:datasets.length>1&&datasets.length<=12,position:\'right\'},',
    "               tooltip:{callbacks:{label:p=>'('+p.parsed.x+', '+p.parsed.y+')'}}},",
    '      scales:{',
    "        x:{title:{display:true,text:xcol+(xrx?' [rx]':'')}},",
    "        y:{title:{display:true,text:ycol+(yrx?' [rx]':'')}}",
    '      }',
    '    }',
    '  });',
    "  document.getElementById('plot-info').textContent=",
    "    r.points.length.toLocaleString()+' pts plotted, '+",
    "    r.skipped+' skipped (non-numeric)'+",
    "    (r.sampled?' [sampled from '+r.total_pts.toLocaleString()+']':'');",
    '}',
    '</script>',
    '</body>',
    "</html>'''",
]

HANDLER_LINES = [
    '',
    '',
    '# ---------------------------------------------------------------------------',
    '# HTTP Handler',
    '# ---------------------------------------------------------------------------',
    'class Handler(BaseHTTPRequestHandler):',
    '',
    '    def do_GET(self):',
    '        parsed = urlparse(self.path)',
    '        path = parsed.path',
    "        if path == '/':",
    '            body = get_html().encode(\'utf-8\')',
    "            self._respond(200, 'text/html; charset=utf-8', body)",
    "        elif path.startswith('/download/'):",
    "            csv_id = path.split('/')[-1]",
    '            if csv_id not in parsed_cache:',
    '                self.send_error(404); return',
    '            data = parsed_cache[csv_id]',
    '            buf = io.StringIO()',
    '            w = csv.writer(buf)',
    "            w.writerow(data['headers'])",
    "            w.writerows(data['rows'])",
    "            body = buf.getvalue().encode('utf-8')",
    '            self.send_response(200)',
    "            self.send_header('Content-Type','text/csv; charset=utf-8')",
    "            self.send_header('Content-Disposition','attachment; filename=fdv_'+csv_id+'.csv')",
    "            self.send_header('Content-Length',len(body))",
    '            self.end_headers(); self.wfile.write(body)',
    "        elif path == '/plot_data':",
    '            self._plot_data(parsed)',
    '        else:',
    '            self.send_error(404)',
    '',
    '    def _plot_data(self, parsed):',
    '        qs = parse_qs(parsed.query)',
    "        def g(k, d=''): return qs.get(k,[d])[0]",
    "        csv_id    = g('csv_id')",
    "        x_col     = g('x_col')",
    "        y_col     = g('y_col')",
    "        x_rx      = g('x_regex') or None",
    "        y_rx      = g('y_regex') or None",
    "        color_col = g('color_col') or None",
    "        max_pts   = int(g('max_points','5000') or 5000)",
    '        if csv_id not in parsed_cache:',
    "            self._json(400, {'success':False,'error':'csv_id not found'}); return",
    '        data = parsed_cache[csv_id]',
    "        headers = data['headers']",
    "        rows    = data['rows']",
    '        try:',
    '            xi = headers.index(x_col)',
    '            yi = headers.index(y_col)',
    '        except ValueError as e:',
    "            self._json(400,{'success':False,'error':str(e)}); return",
    '        ci = headers.index(color_col) if color_col and color_col in headers else None',
    '        points = []; skipped = 0',
    '        for row in rows:',
    "            xv = extract_numeric(row[xi] if xi<len(row) else '', x_rx)",
    "            yv = extract_numeric(row[yi] if yi<len(row) else '', y_rx)",
    '            if xv is None or yv is None:',
    '                skipped += 1; continue',
    "            grp = row[ci] if ci is not None and ci<len(row) else ''",
    "            points.append({'x':xv,'y':yv,'g':grp})",
    '        total_pts = len(points)',
    '        sampled = total_pts > max_pts',
    '        if sampled:',
    '            import random; points = random.sample(points, max_pts)',
    '        self._json(200,{',
    "            'success':True,'points':points,'skipped':skipped,",
    "            'total_pts':total_pts,'sampled':sampled",
    '        })',
    '',
    '    def do_POST(self):',
    "        if self.path != '/parse':",
    '            self.send_error(404); return',
    '        try:',
    "            clen = int(self.headers.get('Content-Length',0))",
    '            body = self.rfile.read(clen)',
    "            ct = self.headers.get('Content-Type','')",
    '            bnd = None',
    "            for part in ct.split(';'):",
    '                part = part.strip()',
    "                if part.startswith('boundary='):",
    '                    bnd = part[9:].strip()',
    '            if not bnd:',
    "                raise ValueError('Missing multipart boundary')",
    "            bnd_bytes = ('--'+bnd).encode()",
    '            parts_list = body.split(bnd_bytes)',
    '            file_content = None',
    "            regex_filter = ''",
    "            mode = 'include'",
    '            for i, part in enumerate(parts_list):',
    '                if i == 0:',
    '                    continue  # skip leading empty (multipart fix)',
    '                if b\'name="file"\' in part and b\'filename=\' in part:',
    "                    lines = part.split(b'\\r\\n')",
    '                    for j, ln in enumerate(lines):',
    "                        if ln == b'':",
    "                            file_content = b'\\r\\n'.join(lines[j+1:-1])",
    '                            break',
    '                elif b\'name="regex"\' in part:',
    "                    lines = part.split(b'\\r\\n')",
    '                    for j, ln in enumerate(lines):',
    "                        if ln == b'':",
    "                            regex_filter = b'\\r\\n'.join(lines[j+1:-1]).decode('utf-8','ignore').strip()",
    '                            break',
    '                elif b\'name="mode"\' in part:',
    "                    lines = part.split(b'\\r\\n')",
    '                    for j, ln in enumerate(lines):',
    "                        if ln == b'':",
    "                            mode = b'\\r\\n'.join(lines[j+1:-1]).decode('utf-8','ignore').strip()",
    '                            break',
    '            if not file_content:',
    "                raise ValueError('No file uploaded')",
    "            tmp = Path(tempfile.gettempdir()) / ('fdv_'+uuid.uuid4().hex+'.log')",
    '            tmp.write_bytes(file_content)',
    '            try:',
    '                headers, rows = parse_log_file(',
    '                    str(tmp),',
    '                    regex_filter or None,',
    "                    include_mode=(mode=='include')",
    '                )',
    '            finally:',
    '                tmp.unlink(missing_ok=True)',
    '            if not rows:',
    "                raise ValueError('No matching rows found')",
    "            csv_id = 'csv_'+uuid.uuid4().hex[:8]",
    "            parsed_cache[csv_id] = {'headers':headers,'rows':rows}",
    '            display_rows = rows[:5000] if len(rows) > 5000 else rows',
    '            self._json(200,{',
    "                'success':True,'csv_id':csv_id,",
    "                'headers':headers,'rows':display_rows,",
    "                'total_rows':len(rows)",
    '            })',
    '        except Exception as e:',
    '            import traceback; traceback.print_exc(file=sys.stderr)',
    "            self._json(400,{'success':False,'error':str(e)})",
    '',
    '    def _respond(self, code, ctype, body):',
    '        self.send_response(code)',
    "        self.send_header('Content-Type', ctype)",
    "        self.send_header('Content-Length', len(body))",
    '        self.end_headers()',
    '        self.wfile.write(body)',
    '',
    '    def _json(self, code, obj):',
    "        body = json.dumps(obj).encode('utf-8')",
    "        self._respond(code, 'application/json; charset=utf-8', body)",
    '',
    '    def log_message(self, fmt, *args):',
    '        pass  # suppress request logging',
    '',
    '',
    'def main():',
    "    print('FDV Chart Parser starting on http://localhost:5058', file=sys.stderr, flush=True)",
    "    server = HTTPServer(('127.0.0.1', 5058), Handler)",
    '    try:',
    '        server.serve_forever()',
    '    except KeyboardInterrupt:',
    '        server.shutdown()',
    '',
    "",
    "if __name__ == '__main__':",
    '    main()',
]

all_lines = LINES + HTML_LINES + HANDLER_LINES

with open(TARGET, 'w', encoding='utf-8', newline='\n') as fh:
    fh.write('\n'.join(all_lines) + '\n')

print(f'Written {TARGET}')
print(f'Lines: {len(all_lines)}')

import py_compile, sys
try:
    py_compile.compile(TARGET, doraise=True)
    print('Syntax: OK')
except py_compile.PyCompileError as e:
    print('SYNTAX ERROR:', e)
    sys.exit(1)

# spot checks
src = open(TARGET).read()
checks = {
    'multipart i==0 fix': 'if i == 0:' in src,
    'WL default': "'WL'" in src,
    'RBER default': "'RBER'" in src,
    'auto-draw': 'setTimeout(drawPlot' in src,
    'display cap 5000': 'rows[:5000]' in src,
    'plot above table': src.index('plot-section') < src.index('table-container'),
    '100vh height': 'calc(100vh' in src,
    'FDV parser': 'parse_fdv_output_line' in src,
    '/plot_data endpoint': 'plot_data' in src,
}
ok = True
for k,v in checks.items():
    print(f"  {'OK  ' if v else 'FAIL'} {k}")
    if not v: ok = False
print('\nAll checks passed!' if ok else '\nSome checks FAILED')
